### ISSUE TITLE
Login and register use different formatting

### ISSUE THREAD

**Issue by pravin-sivabalan** [BoilerMake/frontend#100]
1. Font is different. 
2. Inconsistent placeholder usage

![image](https://user-images.githubusercontent.com/4581341/44070439-7c93956e-9f49-11e8-82fa-2a8c783063bf.png)
![image](https://user-images.githubusercontent.com/4581341/44070458-9270de64-9f49-11e8-871b-b8f5a3d5c499.png)

**Comment by CJEnright** [comment]
Fixed with #103
