### ISSUE TITLE
Navbar issues

### ISSUE THREAD

**Issue by pravin-sivabalan** [BoilerMake/frontend#19]
There are some issues with the nav-left on mobile Chrome where it overlaps the nav-right links. Might want to make it two layered on mobile and have the tabs be fixed.
![screen shot 2017-07-10 at 3 28 01 pm](https://user-images.githubusercontent.com/4581341/28038420-7028e612-6584-11e7-81d0-4c1311f02d6e.png)

On desktop/mobile chrome there isn't a background on the logo, so it overlaps with the text. A fix might just be to make the Boilermake text not fixed, and keep the logo since it's above the margins.
<img width="383" alt="screen shot 2017-07-10 at 3 29 16 pm" src="https://user-images.githubusercontent.com/4581341/28038457-95d7c7f2-6584-11e7-883f-e761c872d8f7.png">

**Comment by avincent6** [comment]
Lol omg I need to finish the nav!

**Comment by nickysemenza** [comment]
fixed on prod now @pravin-sivabalan 👍
