### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by AnkitPatanaik** [BoilerMake/frontend#20]
Currently the favicon on boilermake.org is just the neon outline.  We should change that to be on a dark background or something because it is very difficult to see.

![image](https://user-images.githubusercontent.com/8581373/28043686-dc608fa8-6587-11e7-987f-4627f055e6b5.png)

**Comment by nickysemenza** [comment]
@avincent6 do we have an existing asset that'd work better for this?

**Comment by AnkitPatanaik** [comment]
potentially consider this if neon on black bg looks bad: 

![image](https://user-images.githubusercontent.com/8581373/28043867-eaea491e-6588-11e7-8d10-aa064c873f69.png)
