### ISSUE TITLE
Hard Refresh on Login Screen

### ISSUE THREAD

**Issue by AnkitPatanaik** [BoilerMake/frontend#28]
![image](https://user-images.githubusercontent.com/8581373/28839177-aa2bd4a8-76a7-11e7-9574-030cccfbd5de.png)

Reproduction steps:
1. Hit login button on boilermake.org --> boilermake.org/login
2. Hard refresh (cmd+shift+r)

**Comment by nickysemenza** [comment]
fixed; made cloudfront use index.html as 404 page so that react handles the fact that there really isn't a file called login
