### ISSUE TITLE
Change strings for non checked boxes

### ISSUE THREAD

**Issue by AnkitPatanaik** [BoilerMake/frontend#60]
![image](https://user-images.githubusercontent.com/8581373/30447625-b9545c22-995a-11e7-8673-5f0f361528ac.png)

These are seen if you leave fields incomplete.

T&C 1 -> Please confirm if you are 18 years of age or older.
T&C 2 -> Please confirm if you agree to the MLH Code of Conduct.
T&C 3 -> Please confirm that you agree to both the MLH Contest Terms and Conditions and the MLH Privacy Policy.

**Comment by nickysemenza** [comment]
oh, derp 😛

**Comment by nickysemenza** [comment]
fixed
