### ISSUE TITLE
Specify a fallback font for Helvetica for <p>

### ISSUE THREAD

**Issue by scottopell** [BoilerMake/frontend#84]
On a computer without a helvetica font, it falls back to some default and all the `<p>` text looks really bad.

You should specify a fallback  (or just `inherit`) it should help.

![image](https://user-images.githubusercontent.com/996472/40789779-3f00a20e-64c1-11e8-9101-ba31e2658f00.png)

**Comment by kedarv** [comment]
@pkfoury This issue still exists on computers without Helvetica. Consider adding Arial as a fallback, or better:
```
  font-family: -apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif
```
(https://github.com/necolas/normalize.css/issues/665)
