### ISSUE TITLE
Text blocks lack padding on small screens

### ISSUE THREAD

**Issue by kedarv** [BoilerMake/frontend#90]
![image](https://user-images.githubusercontent.com/1365665/43555748-f63c4016-95b0-11e8-9b04-3a598c88b1db.png)

![image](https://user-images.githubusercontent.com/1365665/43555756-fc26550c-95b0-11e8-81b4-013ab5aee901.png)

![image](https://user-images.githubusercontent.com/1365665/43555762-016f287c-95b1-11e8-9b33-9704c0fdf917.png)

**Comment by pkfoury** [comment]
Browser/Device? It looks as-intended on my Firefox Android

**Comment by pravin-sivabalan** [comment]
squish the width on your desktop browser. gap in the breakpoints?

**Comment by kedarv** [comment]
Try using the chrome device emulator

**Comment by pkfoury** [comment]
Got me there

**Comment by kedarv** [comment]
![image](https://user-images.githubusercontent.com/1365665/43679063-549eea68-97d3-11e8-8a68-70c29ccad3e5.png)

maybe it's broken on desktop too?

**Comment by pkfoury** [comment]
#89 is where the padding broke, not sure where though since it looks like only day-of was touched. cc ~@colejoh~ @CJEnright

**Comment by CJEnright** [comment]
Should be fixed with #92!

**Comment by pkfoury** [comment]
Why do we keep deleting this? In src/assets/index.scss
![screen shot 2018-08-15 at 12 45 21 am](https://user-images.githubusercontent.com/22671016/44132020-94a6b54c-a024-11e8-9bbf-ae3d066daff8.png)

**Comment by colejoh** [comment]
Because we're using the mixin in tools.scss

**Comment by colejoh** [comment]
I guess it got deleted from home

**Comment by colejoh** [comment]
Pushing straight to master, buckle in
