### ISSUE TITLE
Says "Success" on save, even though applications is not complete

### ISSUE THREAD

**Issue by pravin-sivabalan** [BoilerMake/frontend#99]
The popup should be yellow, and say "Saved". It's kind of confusing that it says success, but the application is not complete. 

Reproduce:
1. Sign in with GitHub
2. Save application with missing fields

![image](https://user-images.githubusercontent.com/4581341/44070369-11aaac10-9f49-11e8-8dea-267e798e6fd8.png)

**Comment by CJEnright** [comment]
fixed with #111
